import {
  PenLine,
  Code2,
  Image as ImageIcon,
  Clapperboard,
  AudioLines,
  Database,
  Bot,
  Search,
  type LucideIcon,
} from "lucide-react";

export type AccentColor =
  | "aurora"
  | "star"
  | "nebula"
  | "coral"
  | "teal"
  | "neutral";

export interface Category {
  id: string;
  label: string;
  icon: LucideIcon;
  accent: AccentColor;
  count: number;
  blurb: string;
}

export const categories: Category[] = [
  {
    id: "writing",
    label: "Writing",
    icon: PenLine,
    accent: "aurora",
    count: 0, // computed in getCategoryCounts()
    blurb: "Drafts, copy & long-form",
  },
  {
    id: "coding",
    label: "Coding",
    icon: Code2,
    accent: "teal",
    count: 0,
    blurb: "Copilots & dev agents",
  },
  {
    id: "images",
    label: "Images",
    icon: ImageIcon,
    accent: "nebula",
    count: 0,
    blurb: "Art, design & photo",
  },
  {
    id: "video",
    label: "Video",
    icon: Clapperboard,
    accent: "coral",
    count: 0,
    blurb: "Generation & editing",
  },
  {
    id: "voice",
    label: "Voice",
    icon: AudioLines,
    accent: "star",
    count: 0,
    blurb: "TTS, music & cloning",
  },
  {
    id: "data",
    label: "Data",
    icon: Database,
    accent: "aurora",
    count: 0,
    blurb: "Analysis & research",
  },
  {
    id: "agents",
    label: "Agents",
    icon: Bot,
    accent: "nebula",
    count: 0,
    blurb: "Autonomous workflows",
  },
  {
    id: "search",
    label: "Search",
    icon: Search,
    accent: "teal",
    count: 0,
    blurb: "Answer engines",
  },
];

/**
 * Returns a map of categoryId -> actual number of tools in that category,
 * computed from the real `tools` array. Use this instead of the hardcoded
 * `count` field so the UI always reflects reality.
 */
export function getCategoryCounts(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const c of categories) counts[c.id] = 0;
  for (const t of tools) {
    if (counts[t.category] !== undefined) counts[t.category]++;
  }
  return counts;
}

export type BudgetTier = "Free" | "Freemium" | "$" | "$$" | "$$$";

/** Numeric weight used for "at or below budget" filtering. */
export const budgetRank: Record<BudgetTier, number> = {
  Free: 0,
  Freemium: 1,
  $: 2,
  $$: 3,
  $$$: 4,
};

export interface PricingTier {
  name: string;
  price: string;
  note: string;
}

export interface ToolSpec {
  /** capability label -> boolean or string value */
  [key: string]: string | boolean;
}

export interface AiTool {
  id: string;
  name: string;
  vendor: string;
  logo: string; // single emoji / glyph used inside the 3D logo block
  accent: AccentColor;
  category: string;
  tasks: string[];
  budget: BudgetTier;
  priceNote: string;
  rating: number; // 0 - 5
  reviews: number;
  tagline: string;
  description: string;
  tags: string[];
  featured?: boolean;
  badge?: string;
  launched: string; // year
  pricing: PricingTier[];
  pros: string[];
  cons: string[];
  /** canonical spec keys used in the compare table */
  spec: ToolSpec;
  website: string;
}

/** Canonical capability/spec keys rendered in the compare + detail views. */
export const specKeys: {
  key: string;
  label: string;
  highlight?: boolean;
}[] = [
  { key: "bestFor", label: "Best for" },
  { key: "context", label: "Context window", highlight: true },
  { key: "imageGen", label: "Image generation" },
  { key: "voice", label: "Voice mode" },
  { key: "codeExec", label: "Code execution" },
  { key: "web", label: "Web browsing" },
  { key: "offline", label: "Offline / open weights" },
  { key: "api", label: "Public API" },
  { key: "price", label: "Starting price", highlight: true },
];

export const tools: AiTool[] = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    vendor: "OpenAI",
    logo: "✦",
    accent: "aurora",
    category: "writing",
    tasks: ["Writing", "Agents", "Coding"],
    budget: "Freemium",
    priceNote: "Free · $20/mo Plus",
    rating: 4.8,
    reviews: 18420,
    tagline: "The general-purpose conversational AI for almost any task.",
    description:
      "ChatGPT is the most widely used AI assistant, handling writing, coding, analysis and image generation through a single chat interface. GPT-4o brings realtime voice, vision and a built-in code interpreter to every conversation.",
    tags: ["GPT-4o", "Voice", "Vision", "Code interpreter"],
    featured: true,
    badge: "Most popular",
    launched: "2022",
    pricing: [
      { name: "Free", price: "$0", note: "GPT-4o mini, limited messages" },
      { name: "Plus", price: "$20/mo", note: "GPT-4o, higher limits" },
      { name: "Team", price: "$25/mo", note: "Shared workspace" },
    ],
    pros: [
      "Excellent all-rounder across tasks",
      "Realtime voice & vision",
      "Massive plugin + GPT ecosystem",
    ],
    cons: ["Context caps on free tier", "Usage limits on Plus"],
    spec: {
      bestFor: "General chat & tasks",
      context: "128K",
      imageGen: true,
      voice: true,
      codeExec: true,
      web: true,
      offline: false,
      api: true,
      price: "Free · $20/mo",
    },
    website: "chat.openai.com",
  },
  {
    id: "claude",
    name: "Claude",
    vendor: "Anthropic",
    logo: "✸",
    accent: "star",
    category: "writing",
    tasks: ["Writing", "Coding", "Agents"],
    budget: "Freemium",
    priceNote: "Free · $20/mo Pro",
    rating: 4.8,
    reviews: 9650,
    tagline: "Thoughtful, long-context assistant tuned for nuance and safety.",
    description:
      "Claude is known for its measured, high-quality writing and an industry-leading 200K context window. Artifacts, Projects and computer use make it a favourite for long documents, codebases and careful reasoning.",
    tags: ["200K context", "Artifacts", "Projects"],
    featured: true,
    badge: "Best for long docs",
    launched: "2023",
    pricing: [
      { name: "Free", price: "$0", note: "Sonnet, daily limits" },
      { name: "Pro", price: "$20/mo", note: "Opus access, 5x usage" },
      { name: "Team", price: "$30/mo", note: "Shared projects" },
    ],
    pros: [
      "Best-in-class long-context handling",
      "Superior writing quality",
      "Artifacts for live previews",
    ],
    cons: ["No native image generation", "Tighter content guardrails"],
    spec: {
      bestFor: "Long documents & nuance",
      context: "200K",
      imageGen: false,
      voice: true,
      codeExec: true,
      web: true,
      offline: false,
      api: true,
      price: "Free · $20/mo",
    },
    website: "claude.ai",
  },
  {
    id: "midjourney",
    name: "Midjourney",
    vendor: "Midjourney",
    logo: "◐",
    accent: "nebula",
    category: "images",
    tasks: ["Images"],
    budget: "$",
    priceNote: "From $10/mo",
    rating: 4.7,
    reviews: 7320,
    tagline: "Cinematic, painterly image generation with a signature style.",
    description:
      "Midjourney produces some of the most aesthetically refined AI imagery available. Version 6 adds style references, character consistency and precise pan/zoom controls — all driven from a Discord or web prompt.",
    tags: ["v6", "Style refs", "Pan & zoom"],
    featured: true,
    badge: "Top rated art",
    launched: "2022",
    pricing: [
      { name: "Basic", price: "$10/mo", note: "~200 images" },
      { name: "Standard", price: "$30/mo", note: "15h fast + unlimited relax" },
      { name: "Pro", price: "$60/mo", note: "Stealth + 12h fast" },
    ],
    pros: [
      "Unmatched aesthetic quality",
      "Style & character references",
      "Active community & gallery",
    ],
    cons: ["No free tier", "Discord-first workflow"],
    spec: {
      bestFor: "Artistic image generation",
      context: "—",
      imageGen: true,
      voice: false,
      codeExec: false,
      web: false,
      offline: false,
      api: false,
      price: "From $10/mo",
    },
    website: "midjourney.com",
  },
  {
    id: "cursor",
    name: "Cursor",
    vendor: "Anysphere",
    logo: "⌘",
    accent: "teal",
    category: "coding",
    tasks: ["Coding"],
    budget: "Freemium",
    priceNote: "Free · $20/mo Pro",
    rating: 4.7,
    reviews: 5110,
    tagline: "The AI code editor that understands your whole repository.",
    description:
      "Cursor is a VS Code fork built around AI. It indexes your entire repo for context-aware tab autocomplete, multi-file edits and an agent mode that can plan and execute changes across the codebase.",
    tags: ["Repo context", "Tab autocomplete", "Agent mode"],
    featured: true,
    badge: "Devs' choice",
    launched: "2023",
    pricing: [
      { name: "Hobby", price: "$0", note: "2K completions / mo" },
      { name: "Pro", price: "$20/mo", note: "Unlimited completions" },
      { name: "Business", price: "$40/mo", note: "Admin + privacy mode" },
    ],
    pros: [
      "Deep whole-repo context",
      "Best-in-class autocomplete",
      "Familiar VS Code UX",
    ],
    cons: ["Heavier on resources", "Premium model usage capped"],
    spec: {
      bestFor: "In-editor coding",
      context: "Repo-wide",
      imageGen: false,
      voice: false,
      codeExec: true,
      web: false,
      offline: false,
      api: false,
      price: "Free · $20/mo",
    },
    website: "cursor.sh",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    vendor: "ElevenLabs",
    logo: "ღ",
    accent: "star",
    category: "voice",
    tasks: ["Voice"],
    budget: "Freemium",
    priceNote: "Free · from $5/mo",
    rating: 4.6,
    reviews: 4280,
    tagline: "Hyper-realistic text-to-speech, voice cloning & dubbing.",
    description:
      "ElevenLabs sets the bar for natural synthetic speech. Generate voices in 32 languages, clone a voice from a short sample, and dub full videos with lip-synced translation in minutes.",
    tags: ["32 langs", "Voice clone", "Realtime"],
    featured: true,
    launched: "2022",
    pricing: [
      { name: "Free", price: "$0", note: "10K chars / mo" },
      { name: "Starter", price: "$5/mo", note: "30K chars + voice clone" },
      { name: "Creator", price: "$22/mo", note: "100K chars, commercial" },
    ],
    pros: [
      "Most realistic TTS available",
      "Instant voice cloning",
      "Multilingual dubbing",
    ],
    cons: ["Char-based pricing adds up", "Clone quality varies by sample"],
    spec: {
      bestFor: "Voice & dubbing",
      context: "—",
      imageGen: false,
      voice: true,
      codeExec: false,
      web: false,
      offline: false,
      api: true,
      price: "Free · from $5/mo",
    },
    website: "elevenlabs.io",
  },
  {
    id: "runway",
    name: "Runway",
    vendor: "Runway",
    logo: "▷",
    accent: "coral",
    category: "video",
    tasks: ["Video"],
    budget: "$",
    priceNote: "From $15/mo",
    rating: 4.5,
    reviews: 3990,
    tagline: "Generate and direct video from a single text prompt.",
    description:
      "Runway's Gen-3 Alpha turns text and images into high-fidelity video. Motion brush, camera controls and image-to-video give directors fine-grained control over every shot.",
    tags: ["Gen-3", "Image-to-video", "Motion brush"],
    featured: true,
    launched: "2020",
    pricing: [
      { name: "Standard", price: "$15/mo", note: "625 credits" },
      { name: "Pro", price: "$35/mo", note: "2250 credits" },
      { name: "Unlimited", price: "$95/mo", note: "Unlimited Gen-3" },
    ],
    pros: [
      "Leading text-to-video quality",
      "Precise camera & motion control",
      "Strong image-to-video",
    ],
    cons: ["Credits burn fast", "Steep learning curve"],
    spec: {
      bestFor: "Text-to-video",
      context: "—",
      imageGen: false,
      voice: false,
      codeExec: false,
      web: false,
      offline: false,
      api: true,
      price: "From $15/mo",
    },
    website: "runwayml.com",
  },
  {
    id: "gemini",
    name: "Gemini",
    vendor: "Google",
    logo: "✧",
    accent: "aurora",
    category: "agents",
    tasks: ["Writing", "Data", "Agents"],
    budget: "Freemium",
    priceNote: "Free · $20/mo Advanced",
    rating: 4.6,
    reviews: 12100,
    tagline: "Multimodal model with deep Google Workspace integration.",
    description:
      "Gemini is Google's flagship multimodal model with a 1M-token context window. It powers AI features across Docs, Gmail, Sheets and Android, and integrates directly with Search for grounded answers.",
    tags: ["1M context", "Multimodal", "Workspace"],
    launched: "2023",
    pricing: [
      { name: "Free", price: "$0", note: "Flash model" },
      { name: "Advanced", price: "$20/mo", note: "Pro + 2TB storage" },
      { name: "AI Pro", price: "$200/mo", note: "Highest limits" },
    ],
    pros: [
      "Massive 1M context",
      "Native Google Workspace tie-in",
      "Strong multimodal grounding",
    ],
    cons: ["Less consistent tone", "Region-restricted features"],
    spec: {
      bestFor: "Google ecosystem",
      context: "1M",
      imageGen: true,
      voice: true,
      codeExec: true,
      web: true,
      offline: false,
      api: true,
      price: "Free · $20/mo",
    },
    website: "gemini.google.com",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    vendor: "Perplexity",
    logo: "◉",
    accent: "teal",
    category: "search",
    tasks: ["Search", "Data"],
    budget: "Freemium",
    priceNote: "Free · $20/mo Pro",
    rating: 4.6,
    reviews: 6740,
    tagline: "Answer engine that cites live sources for every response.",
    description:
      "Perplexity is an answer engine that searches the live web and writes cited responses. Pro search breaks complex questions into steps, and the Pro tier unlocks frontier models like GPT-4o and Claude.",
    tags: ["Live web", "Citations", "Pro search"],
    launched: "2022",
    pricing: [
      { name: "Free", price: "$0", note: "5 Pro searches / 4h" },
      { name: "Pro", price: "$20/mo", note: "Unlimited + model choice" },
      { name: "Enterprise", price: "$40/mo", note: "SSO + data privacy" },
    ],
    pros: [
      "Always-cited, current answers",
      "Multi-step Pro search",
      "Pick the underlying model",
    ],
    cons: ["Less creative for long-form", "Free tier is rate-limited"],
    spec: {
      bestFor: "Answer engine",
      context: "—",
      imageGen: false,
      voice: true,
      codeExec: false,
      web: true,
      offline: false,
      api: true,
      price: "Free · $20/mo",
    },
    website: "perplexity.ai",
  },
  {
    id: "dalle3",
    name: "DALL·E 3",
    vendor: "OpenAI",
    logo: "◆",
    accent: "nebula",
    category: "images",
    tasks: ["Images"],
    budget: "Freemium",
    priceNote: "Free in ChatGPT · $20/mo",
    rating: 4.4,
    reviews: 5810,
    tagline: "Prompt-faithful image generation built into ChatGPT.",
    description:
      "DALL·E 3 excels at following complex prompts and rendering legible text inside images. Available free inside ChatGPT, it makes image generation a natural part of any conversation.",
    tags: ["Prompt fidelity", "Text in images", "ChatGPT native"],
    launched: "2023",
    pricing: [
      { name: "Free", price: "$0", note: "2/day in ChatGPT" },
      { name: "Plus", price: "$20/mo", note: "Higher limits + editing" },
    ],
    pros: [
      "Excellent prompt adherence",
      "Reads text in images reliably",
      "No separate subscription",
    ],
    cons: ["Less artistic than Midjourney", "Locked to OpenAI ecosystem"],
    spec: {
      bestFor: "Prompt-faithful images",
      context: "—",
      imageGen: true,
      voice: false,
      codeExec: false,
      web: false,
      offline: false,
      api: true,
      price: "Free · $20/mo",
    },
    website: "openai.com/dall-e-3",
  },
  {
    id: "suno",
    name: "Suno",
    vendor: "Suno",
    logo: "♪",
    accent: "star",
    category: "voice",
    tasks: ["Voice"],
    budget: "Freemium",
    priceNote: "Free · $10/mo Pro",
    rating: 4.5,
    reviews: 3120,
    tagline: "Generate full songs with vocals from a single line of text.",
    description:
      "Suno turns a prompt into a complete song — lyrics, vocals, instruments and all. The Pro and Premier tiers unlock commercial rights and higher daily generation limits.",
    tags: ["Full songs", "Vocals", "Commercial use"],
    launched: "2023",
    pricing: [
      { name: "Free", price: "$0", note: "10 songs / day" },
      { name: "Pro", price: "$10/mo", note: "2500 credits + comm. rights" },
      { name: "Premier", price: "$30/mo", note: "10000 credits" },
    ],
    pros: [
      "Complete songs with vocals",
      "Surprisingly natural production",
      "Generous free tier",
    ],
    cons: ["Vocal clarity can vary", "Genre coverage still growing"],
    spec: {
      bestFor: "Music generation",
      context: "—",
      imageGen: false,
      voice: true,
      codeExec: false,
      web: false,
      offline: false,
      api: false,
      price: "Free · $10/mo",
    },
    website: "suno.com",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    vendor: "GitHub",
    logo: "⌥",
    accent: "teal",
    category: "coding",
    tasks: ["Coding"],
    budget: "$",
    priceNote: "From $10/mo",
    rating: 4.5,
    reviews: 8890,
    tagline: "The OG AI pair programmer, deeply integrated into your IDE.",
    description:
      "GitHub Copilot suggests whole lines and functions inside VS Code, JetBrains and Neovim. Copilot Chat and the new agent mode bring repo-aware refactoring and autonomous task execution.",
    tags: ["IDE native", "Copilot Chat", "Agent mode"],
    launched: "2021",
    pricing: [
      { name: "Free", price: "$0", note: "2000 completions / mo" },
      { name: "Pro", price: "$10/mo", note: "Unlimited + chat" },
      { name: "Business", price: "$19/mo", note: "Org policy + privacy" },
    ],
    pros: [
      "Broadest IDE support",
      "Free tier available",
      "Backed by GitHub's code corpus",
    ],
    cons: ["Less repo context than Cursor", "Agent mode is newer"],
    spec: {
      bestFor: "IDE pair programming",
      context: "File + chat",
      imageGen: false,
      voice: false,
      codeExec: true,
      web: false,
      offline: false,
      api: true,
      price: "Free · $10/mo",
    },
    website: "github.com/features/copilot",
  },
  {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    vendor: "Stability AI",
    logo: "▰",
    accent: "coral",
    category: "images",
    tasks: ["Images"],
    budget: "Free",
    priceNote: "Free / open weights",
    rating: 4.3,
    reviews: 6240,
    tagline: "Open-weights image model you can run locally and fine-tune.",
    description:
      "Stable Diffusion is the open-source backbone of the AI image world. Run it locally with ComfyUI or Automatic1111, fine-tune custom checkpoints, and own your pipeline end to end.",
    tags: ["Open weights", "Local run", "Fine-tunable"],
    launched: "2022",
    pricing: [
      { name: "Community", price: "$0", note: "Run locally, free" },
      { name: "Creator", price: "$9/mo", note: "Stability API credits" },
      { name: "Pro", price: "$49/mo", note: "Higher throughput" },
    ],
    pros: [
      "Fully open weights",
      "Runs offline on your GPU",
      "Endless community models",
    ],
    cons: ["Requires GPU + setup", "Quality behind Midjourney v6"],
    spec: {
      bestFor: "Open & local image gen",
      context: "—",
      imageGen: true,
      voice: false,
      codeExec: false,
      web: false,
      offline: true,
      api: true,
      price: "Free / open",
    },
    website: "stability.ai",
  },
  {
    id: "synthesia",
    name: "Synthesia",
    vendor: "Synthesia",
    logo: "▣",
    accent: "coral",
    category: "video",
    tasks: ["Video"],
    budget: "$$",
    priceNote: "From $22/mo",
    rating: 4.4,
    reviews: 2180,
    tagline: "Studio-quality talking-head videos from a script, no camera.",
    description:
      "Synthesia turns a written script into a polished video presented by a lifelike AI avatar. Ideal for training, onboarding and explainer content across 140+ languages.",
    tags: ["AI avatars", "140+ langs", "Corporate video"],
    launched: "2017",
    pricing: [
      { name: "Starter", price: "$22/mo", note: "120 min / year" },
      { name: "Creator", price: "$67/mo", note: "360 min + avatar clone" },
      { name: "Enterprise", price: "Custom", note: "SSO + custom avatars" },
    ],
    pros: [
      "Best-in-class AI avatars",
      "Massive language coverage",
      "No filming required",
    ],
    cons: ["Pricier than generative video", "Less creative freedom"],
    spec: {
      bestFor: "Avatar & training video",
      context: "—",
      imageGen: false,
      voice: true,
      codeExec: false,
      web: false,
      offline: false,
      api: true,
      price: "From $22/mo",
    },
    website: "synthesia.io",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    vendor: "DeepSeek",
    logo: "◈",
    accent: "aurora",
    category: "coding",
    tasks: ["Coding", "Data"],
    budget: "Free",
    priceNote: "Free / open weights",
    rating: 4.4,
    reviews: 4520,
    tagline: "Frontier-class reasoning model with open weights, near-free API.",
    description:
      "DeepSeek's R1 reasoning model rivals frontier labs on math and code at a fraction of the cost — and the weights are open. A top pick for builders who want capability without vendor lock-in.",
    tags: ["Open weights", "Reasoning", "Low-cost API"],
    launched: "2023",
    pricing: [
      { name: "Free", price: "$0", note: "Open weights, self-host" },
      { name: "API", price: "$0.27/M", note: "Input token pricing" },
    ],
    pros: [
      "Open weights, self-hostable",
      "Extremely cheap API",
      "Strong math & code reasoning",
    ],
    cons: ["No first-party app/UX", "Smaller tool ecosystem"],
    spec: {
      bestFor: "Open reasoning & code",
      context: "128K",
      imageGen: false,
      voice: false,
      codeExec: true,
      web: false,
      offline: true,
      api: true,
      price: "Free / open",
    },
    website: "deepseek.com",
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    vendor: "Notion",
    logo: "❏",
    accent: "star",
    category: "writing",
    tasks: ["Writing", "Data"],
    budget: "$",
    priceNote: "From $10/mo",
    rating: 4.3,
    reviews: 3640,
    tagline: "AI built into the workspace where your notes already live.",
    description:
      "Notion AI writes, summarises and transforms content inside your existing docs and databases. Ask questions across your workspace, auto-fill database properties, and draft without leaving context.",
    tags: ["Workspace AI", "Q&A", "Auto-fill"],
    launched: "2023",
    pricing: [
      { name: "Add-on", price: "$10/mo", note: "Per member, on any plan" },
      { name: "Business", price: "$20/mo", note: "Includes AI + admin" },
    ],
    pros: [
      "Lives where your knowledge already is",
      "Cross-workspace Q&A",
      "Database auto-fill",
    ],
    cons: ["Per-seat pricing", "Weakest on pure chat"],
    spec: {
      bestFor: "Workspace writing",
      context: "Workspace-wide",
      imageGen: false,
      voice: false,
      codeExec: false,
      web: true,
      offline: false,
      api: false,
      price: "From $10/mo",
    },
    website: "notion.so/product/ai",
  },
  {
    id: "sora",
    name: "Sora",
    vendor: "OpenAI",
    logo: "⏵",
    accent: "nebula",
    category: "video",
    tasks: ["Video"],
    budget: "$$",
    priceNote: "Included in $20/mo Plus",
    rating: 4.2,
    reviews: 1980,
    tagline: "Long-form, physics-aware video generation from OpenAI.",
    description:
      "Sora generates up to 20-second HD video clips with consistent characters and surprising physical plausibility. Storyboard tools let you stitch clips into structured sequences.",
    tags: ["Long clips", "Storyboard", "HD output"],
    launched: "2024",
    pricing: [
      { name: "Plus", price: "$20/mo", note: "50 prioritized 5s clips" },
      { name: "Pro", price: "$200/mo", note: "Unlimited + 20s 1080p" },
    ],
    pros: [
      "Longer, more coherent clips",
      "Storyboard stitching",
      "Strong physical plausibility",
    ],
    cons: ["Limited availability", "Credit limits on Plus"],
    spec: {
      bestFor: "Long-form AI video",
      context: "—",
      imageGen: false,
      voice: false,
      codeExec: false,
      web: false,
      offline: false,
      api: false,
      price: "$20/mo Plus",
    },
    website: "openai.com/sora",
  },
  {
    id: "grok",
    name: "Grok",
    vendor: "xAI",
    logo: "✕",
    accent: "star",
    category: "writing",
    tasks: ["Writing", "Agents", "Search"],
    budget: "Freemium",
    priceNote: "Free · $30/mo SuperGrok",
    rating: 4.4,
    reviews: 4120,
    tagline: "Witty, real-time-aware assistant with live X integration.",
    description:
      "Grok is xAI's flagship model, known for its irreverent tone and real-time access to posts on X. Grok 4 brings frontier-class reasoning plus an image generator (Grok Imagine) and a coding agent.",
    tags: ["Realtime X", "Grok Imagine", "Reasoning"],
    launched: "2023",
    pricing: [
      { name: "Free", price: "$0", note: "Limited messages on X" },
      { name: "SuperGrok", price: "$30/mo", note: "Higher limits + Imagine" },
      { name: "SuperGrok Heavy", price: "$300/mo", note: "Max throughput" },
    ],
    pros: ["Live access to X data", "Less filtered tone", "Strong reasoning"],
    cons: ["Smaller ecosystem", "Tied to X platform"],
    spec: {
      bestFor: "Realtime + unfiltered chat",
      context: "256K",
      imageGen: true,
      voice: true,
      codeExec: true,
      web: true,
      offline: false,
      api: true,
      price: "Free · $30/mo",
    },
    website: "x.ai/grok",
  },
  {
    id: "ms-copilot",
    name: "Microsoft Copilot",
    vendor: "Microsoft",
    logo: "◐",
    accent: "teal",
    category: "writing",
    tasks: ["Writing", "Data", "Agents"],
    budget: "Freemium",
    priceNote: "Free · $20/mo Pro",
    rating: 4.3,
    reviews: 7210,
    tagline: "GPT-powered assistant baked into Windows, Edge & Office.",
    description:
      "Microsoft Copilot brings GPT-4 class models directly into Windows, Edge, Microsoft 365 and GitHub. It can summarize docs, draft emails, analyze Excel data and generate images — all grounded in your work content.",
    tags: ["M365", "Windows", "GPT-4o"],
    launched: "2023",
    pricing: [
      { name: "Free", price: "$0", note: "Web + Windows chat" },
      { name: "Pro", price: "$20/mo", note: "Copilot in M365 apps" },
      { name: "Business", price: "$30/mo", note: "Per user, commercial" },
    ],
    pros: ["Deep Office integration", "Free on Windows", "Enterprise-grade"],
    cons: ["Best features need M365", "Region-restricted"],
    spec: {
      bestFor: "Microsoft ecosystem",
      context: "128K",
      imageGen: true,
      voice: true,
      codeExec: true,
      web: true,
      offline: false,
      api: true,
      price: "Free · $20/mo",
    },
    website: "copilot.microsoft.com",
  },
  {
    id: "llama",
    name: "Llama 4",
    vendor: "Meta",
    logo: "◑",
    accent: "aurora",
    category: "writing",
    tasks: ["Writing", "Coding", "Agents"],
    budget: "Free",
    priceNote: "Free / open weights",
    rating: 4.5,
    reviews: 5830,
    tagline: "Meta's open-weights frontier model family — Scout to Behemoth.",
    description:
      "Llama 4 is Meta's open model family spanning Scout (efficient), Maverick (balanced) and Behemoth (frontier). Run them locally, fine-tune on your data, or use via partner clouds — no vendor lock-in.",
    tags: ["Open weights", "Fine-tunable", "Multi-modal"],
    launched: "2025",
    pricing: [
      { name: "Open weights", price: "$0", note: "Self-host, free" },
      { name: "Hosted API", price: "varies", note: "Via AWS / Azure / Groq" },
    ],
    pros: ["Fully open weights", "Runs on consumer GPUs (Scout)", "Huge community"],
    cons: ["Self-hosting needs infra", "No first-party chat app"],
    spec: {
      bestFor: "Open & self-hosted LLM",
      context: "10M",
      imageGen: false,
      voice: false,
      codeExec: true,
      web: false,
      offline: true,
      api: true,
      price: "Free / open",
    },
    website: "llama.com",
  },
  {
    id: "mistral",
    name: "Mistral Large",
    vendor: "Mistral AI",
    logo: "◆",
    accent: "coral",
    category: "writing",
    tasks: ["Writing", "Coding"],
    budget: "Freemium",
    priceNote: "Free · $2/M tokens API",
    rating: 4.4,
    reviews: 2980,
    tagline: "European frontier LLM with strong multilingual + code skills.",
    description:
      "Mistral Large is the flagship from Paris-based Mistral AI. It rivals GPT-4 on reasoning and code while offering open weights (Mistral, Mixtral) and a cheap, fast hosted API with strong EU data residency.",
    tags: ["Multilingual", "Mixtral MoE", "EU-hosted"],
    launched: "2023",
    pricing: [
      { name: "Free (Le Chat)", price: "$0", note: "Web chat" },
      { name: "API", price: "$2/M", note: "Per million input tokens" },
      { name: "Enterprise", price: "Custom", note: "Dedicated + on-prem" },
    ],
    pros: ["Excellent multilingual", "Open-weights option", "EU data residency"],
    cons: ["Smaller ecosystem than OpenAI", "Weaker at vision"],
    spec: {
      bestFor: "Multilingual + EU compliance",
      context: "128K",
      imageGen: false,
      voice: false,
      codeExec: true,
      web: true,
      offline: true,
      api: true,
      price: "Free · $2/M tok",
    },
    website: "mistral.ai",
  },
  {
    id: "command-r",
    name: "Command R+",
    vendor: "Cohere",
    logo: "▲",
    accent: "teal",
    category: "data",
    tasks: ["Data", "Search", "Agents"],
    budget: "Freemium",
    priceNote: "Free trial · API from $2/M",
    rating: 4.3,
    reviews: 1640,
    tagline: "Enterprise RAG model tuned for retrieval and tool use.",
    description:
      "Command R+ is Cohere's retrieval-optimized model built for production RAG pipelines and tool-using agents. It cites sources, calls functions and scales to billions of documents with Cohere's search infrastructure.",
    tags: ["RAG-optimized", "Tool use", "Citations"],
    launched: "2024",
    pricing: [
      { name: "Trial", price: "$0", note: "1000 calls / month" },
      { name: "Production", price: "$2/M", note: "Per million tokens" },
      { name: "Enterprise", price: "Custom", note: "Dedicated + support" },
    ],
    pros: ["Best-in-class RAG", "Strong tool/function calling", "Enterprise support"],
    cons: ["Not a chat-first product", "No consumer app"],
    spec: {
      bestFor: "Enterprise RAG & agents",
      context: "128K",
      imageGen: false,
      voice: false,
      codeExec: true,
      web: true,
      offline: false,
      api: true,
      price: "Free trial · $2/M",
    },
    website: "cohere.com/command",
  },
  {
    id: "firefly",
    name: "Adobe Firefly",
    vendor: "Adobe",
    logo: "✺",
    accent: "coral",
    category: "images",
    tasks: ["Images"],
    budget: "Freemium",
    priceNote: "Free · from $9.99/mo",
    rating: 4.4,
    reviews: 4470,
    tagline: "Commercially-safe image generation inside Adobe apps.",
    description:
      "Firefly is Adobe's generative image model, trained only on licensed content for commercial safety. It powers Generative Fill in Photoshop and text-to-image across Express, Illustrator and the web app.",
    tags: ["Commercial-safe", "Photoshop", "Generative Fill"],
    launched: "2023",
    pricing: [
      { name: "Free", price: "$0", note: "25 monthly credits" },
      { name: "Standard", price: "$9.99/mo", note: "2000 credits" },
      { name: "Pro", price: "$29.99/mo", note: "7000 credits" },
    ],
    pros: ["Commercially licensed training data", "Deep Adobe integration", "Vector + photo output"],
    cons: ["Credits burn quickly", "Less artistic than Midjourney"],
    spec: {
      bestFor: "Commercial-safe images",
      context: "—",
      imageGen: true,
      voice: false,
      codeExec: false,
      web: false,
      offline: false,
      api: true,
      price: "Free · $9.99/mo",
    },
    website: "firefly.adobe.com",
  },
  {
    id: "ideogram",
    name: "Ideogram",
    vendor: "Ideogram",
    logo: "▩",
    accent: "star",
    category: "images",
    tasks: ["Images"],
    budget: "Freemium",
    priceNote: "Free · from $8/mo",
    rating: 4.5,
    reviews: 2310,
    tagline: "The image model that actually renders text correctly.",
    description:
      "Ideogram specializes in generating images with legible, accurate text — logos, posters, UI mockups and typography. Its magic prompt expansion and style references make it a designer favourite.",
    tags: ["Text in images", "Logos", "Magic prompt"],
    launched: "2023",
    pricing: [
      { name: "Free", price: "$0", note: "~10 images / day" },
      { name: "Plus", price: "$8/mo", note: "400 priority images" },
      { name: "Pro", price: "$20/mo", note: "Unlimited + upscale" },
    ],
    pros: ["Best at rendering text", "Great for logos/posters", "Generous free tier"],
    cons: ["Less photorealistic than MJ", "Smaller community"],
    spec: {
      bestFor: "Text & logo images",
      context: "—",
      imageGen: true,
      voice: false,
      codeExec: false,
      web: false,
      offline: false,
      api: true,
      price: "Free · $8/mo",
    },
    website: "ideogram.ai",
  },
  {
    id: "leonardo",
    name: "Leonardo AI",
    vendor: "Leonado.AI",
    logo: "⚜",
    accent: "nebula",
    category: "images",
    tasks: ["Images"],
    budget: "Freemium",
    priceNote: "Free · from $10/mo",
    rating: 4.4,
    reviews: 5190,
    tagline: "Game-asset and art generation with fine-tuned models.",
    description:
      "Leonardo AI offers dozens of fine-tuned image models for game assets, concept art, character design and product shots. Its canvas editor, upscaler and motion features round out a complete art pipeline.",
    tags: ["Game assets", "Fine-tuned", "Canvas editor"],
    launched: "2023",
    pricing: [
      { name: "Free", price: "$0", note: "150 daily tokens" },
      { name: "Apprentice", price: "$10/mo", note: "8500 tokens" },
      { name: "Artisan", price: "$24/mo", note: "25000 tokens" },
    ],
    pros: ["Many specialized models", "Built-in canvas + upscaler", "Strong for game art"],
    cons: ["Token system confusing", "Quality behind FLUX/MJ"],
    spec: {
      bestFor: "Game & concept art",
      context: "—",
      imageGen: true,
      voice: false,
      codeExec: false,
      web: false,
      offline: false,
      api: true,
      price: "Free · $10/mo",
    },
    website: "leonardo.ai",
  },
  {
    id: "imagen",
    name: "Imagen 4",
    vendor: "Google",
    logo: "◈",
    accent: "aurora",
    category: "images",
    tasks: ["Images"],
    budget: "$",
    priceNote: "Included in Gemini Advanced",
    rating: 4.3,
    reviews: 1880,
    tagline: "Google's photorealistic image model with sharp text.",
    description:
      "Imagen 4 generates high-fidelity, photorealistic images with notably accurate text rendering and fine detail. Access it through Gemini, Google AI Studio or Vertex AI.",
    tags: ["Photoreal", "Text accuracy", "Vertex AI"],
    launched: "2025",
    pricing: [
      { name: "Gemini Advanced", price: "$20/mo", note: "Includes Imagen" },
      { name: "Vertex AI", price: "$0.04/img", note: "Pay per image" },
    ],
    pros: ["Excellent photorealism", "Accurate text in images", "Enterprise via Vertex"],
    cons: ["No standalone free tier", "Locked to Google ecosystem"],
    spec: {
      bestFor: "Photorealistic images",
      context: "—",
      imageGen: true,
      voice: false,
      codeExec: false,
      web: false,
      offline: false,
      api: true,
      price: "$20/mo Advanced",
    },
    website: "deepmind.google/technologies/imagen",
  },
  {
    id: "flux",
    name: "FLUX.1",
    vendor: "Black Forest Labs",
    logo: "▦",
    accent: "nebula",
    category: "images",
    tasks: ["Images"],
    budget: "Freemium",
    priceNote: "Free (Schnell) · Pro API",
    rating: 4.7,
    reviews: 3920,
    tagline: "Open-weights image model rivaling Midjourney on quality.",
    description:
      "FLUX.1 from Black Forest Labs (ex-Stability team) delivers Midjourney-class image quality with open weights. The Schnell variant runs locally for free; Pro is available via API.",
    tags: ["Open weights", "Schnell", "MJ-class quality"],
    launched: "2024",
    pricing: [
      { name: "Schnell (open)", price: "$0", note: "Run locally, free" },
      { name: "Pro API", price: "$0.05/img", note: "Highest quality" },
      { name: "Dev", price: "$0.03/img", note: "Balanced" },
    ],
    pros: ["Open weights (Schnell)", "Stunning quality", "Local + API options"],
    cons: ["Pro not self-hostable", "Needs decent GPU locally"],
    spec: {
      bestFor: "Open high-quality images",
      context: "—",
      imageGen: true,
      voice: false,
      codeExec: false,
      web: false,
      offline: true,
      api: true,
      price: "Free / open",
    },
    website: "blackforestlabs.ai",
  },
  {
    id: "veo",
    name: "Veo 3.1",
    vendor: "Google",
    logo: "▷",
    accent: "teal",
    category: "video",
    tasks: ["Video"],
    budget: "$$",
    priceNote: "Included in $20/mo Advanced",
    rating: 4.6,
    reviews: 1640,
    tagline: "Google's flagship video model with synchronized audio.",
    description:
      "Veo 3.1 generates high-definition video with native, lip-synced dialogue and sound effects — a first for AI video. Access it through Gemini, Flow or the Vertex API.",
    tags: ["Native audio", "1080p", "Flow editor"],
    launched: "2025",
    pricing: [
      { name: "Advanced", price: "$20/mo", note: "Limited Veo clips" },
      { name: "Pro", price: "$200/mo", note: "More + 4K" },
      { name: "Vertex API", price: "$0.40/sec", note: "Pay per second" },
    ],
    pros: ["Generates audio + dialogue", "Excellent physics", "Google ecosystem"],
    cons: ["Limited on Plus tier", "Region-restricted"],
    spec: {
      bestFor: "Video with synced audio",
      context: "—",
      imageGen: false,
      voice: true,
      codeExec: false,
      web: false,
      offline: false,
      api: true,
      price: "$20/mo Advanced",
    },
    website: "deepmind.google/technologies/veo",
  },
  {
    id: "kling",
    name: "Kling 3.0",
    vendor: "Kuaishou",
    logo: "◭",
    accent: "coral",
    category: "video",
    tasks: ["Video"],
    budget: "$",
    priceNote: "From $10/mo",
    rating: 4.4,
    reviews: 2110,
    tagline: "Long, fluid AI video with strong motion control.",
    description:
      "Kling 3.0 from Kuaishou generates up to 2-minute 1080p video clips with smooth motion, camera control and start/end frame pairing — a top contender for creative video generation.",
    tags: ["2-min clips", "Camera control", "1080p"],
    launched: "2024",
    pricing: [
      { name: "Free", price: "$0", note: "6 daily credits" },
      { name: "Standard", price: "$10/mo", note: "66 credits" },
      { name: "Pro", price: "$35/mo", note: "300 credits" },
    ],
    pros: ["Longest clip duration", "Strong motion", "Generous free credits"],
    cons: ["UI in translation", "Credit burn on long clips"],
    spec: {
      bestFor: "Long creative video",
      context: "—",
      imageGen: false,
      voice: false,
      codeExec: false,
      web: false,
      offline: false,
      api: true,
      price: "From $10/mo",
    },
    website: "klingai.com",
  },
  {
    id: "pika",
    name: "Pika 2.0",
    vendor: "Pika Labs",
    logo: "◓",
    accent: "nebula",
    category: "video",
    tasks: ["Video"],
    budget: "Freemium",
    priceNote: "Free · from $10/mo",
    rating: 4.3,
    reviews: 2740,
    tagline: "Playful, fast text-to-video with Pikaffects effects.",
    description:
      "Pika 2.0 turns prompts and images into short, stylized video clips. Its signature Pikaffects (inflate, melt, explode) make it the most fun AI video tool for social creators.",
    tags: ["Pikaffects", "Social-ready", "Image-to-video"],
    launched: "2023",
    pricing: [
      { name: "Free", price: "$0", note: "Daily credits" },
      { name: "Standard", price: "$10/mo", note: "700 credits" },
      { name: "Pro", price: "$35/mo", note: "2300 credits" },
    ],
    pros: ["Fast generations", "Fun creative effects", "Easy for beginners"],
    cons: ["Shorter clips than Kling", "Less realistic than Veo"],
    spec: {
      bestFor: "Fun social video",
      context: "—",
      imageGen: false,
      voice: false,
      codeExec: false,
      web: false,
      offline: false,
      api: false,
      price: "Free · $10/mo",
    },
    website: "pika.art",
  },
  {
    id: "luma",
    name: "Luma Ray3",
    vendor: "Luma Labs",
    logo: "✧",
    accent: "star",
    category: "video",
    tasks: ["Video"],
    budget: "Freemium",
    priceNote: "Free · from $9.99/mo",
    rating: 4.4,
    reviews: 1820,
    tagline: "Cinematic AI video with smooth camera moves.",
    description:
      "Luma Ray3 generates photorealistic video with smooth, cinematic camera motion and strong physical consistency. Its Dream Machine interface and keyframe control appeal to filmmakers.",
    tags: ["Cinematic", "Camera moves", "Keyframes"],
    launched: "2024",
    pricing: [
      { name: "Free", price: "$0", note: "30 generations / mo" },
      { name: "Plus", price: "$9.99/mo", note: "120 generations" },
      { name: "Premier", price: "$29.99/mo", note: "400 generations" },
    ],
    pros: ["Smooth cinematic motion", "Clean keyframe UX", "Good free tier"],
    cons: ["Shorter clips", "Queue times on free"],
    spec: {
      bestFor: "Cinematic video",
      context: "—",
      imageGen: false,
      voice: false,
      codeExec: false,
      web: false,
      offline: false,
      api: true,
      price: "Free · $9.99/mo",
    },
    website: "lumalabs.ai/ray",
  },
  {
    id: "murf",
    name: "Murf AI",
    vendor: "Murf",
    logo: "▤",
    accent: "teal",
    category: "voice",
    tasks: ["Voice"],
    budget: "Freemium",
    priceNote: "Free · from $19/mo",
    rating: 4.4,
    reviews: 3380,
    tagline: "Studio-grade TTS with a built-in voiceover editor.",
    description:
      "Murf AI combines natural text-to-speech with a timeline editor, letting you build voiceovers for videos, e-learning and ads without recording. 200+ voices, pitch & emphasis control, and a sync-to-video tool.",
    tags: ["200+ voices", "Timeline editor", "Sync to video"],
    launched: "2020",
    pricing: [
      { name: "Free", price: "$0", note: "10 min / 3 voices" },
      { name: "Creator", price: "$19/mo", note: "2h + 120 voices" },
      { name: "Business", price: "$66/mo", note: "Unlimited + team" },
    ],
    pros: ["Built-in editor", "Huge voice library", "Great for e-learning"],
    cons: ["Pricier than ElevenLabs", "Cloning needs higher tier"],
    spec: {
      bestFor: "Voiceover production",
      context: "—",
      imageGen: false,
      voice: true,
      codeExec: false,
      web: false,
      offline: false,
      api: true,
      price: "Free · $19/mo",
    },
    website: "murf.ai",
  },
  {
    id: "play-ht",
    name: "Play.ht",
    vendor: "PlayHT",
    logo: "▥",
    accent: "coral",
    category: "voice",
    tasks: ["Voice"],
    budget: "Freemium",
    priceNote: "Free · from $31/mo",
    rating: 4.3,
    reviews: 2110,
    tagline: "Ultra-realistic TTS with instant voice cloning.",
    description:
      "Play.ht offers ultra-realistic text-to-speech in 140+ languages, instant voice cloning from a short sample, and a low-latency realtime API for conversational agents.",
    tags: ["140+ langs", "Realtime API", "Voice clone"],
    launched: "2016",
    pricing: [
      { name: "Free", price: "$0", note: "12500 chars / month" },
      { name: "Creator", price: "$31/mo", note: "250K chars + clone" },
      { name: "Unlimited", price: "$99/mo", note: "Unlimited generation" },
    ],
    pros: ["Wide language coverage", "Realtime streaming API", "Instant cloning"],
    cons: ["UI feels dated", "Best voices on higher tiers"],
    spec: {
      bestFor: "Realtime TTS + cloning",
      context: "—",
      imageGen: false,
      voice: true,
      codeExec: false,
      web: false,
      offline: false,
      api: true,
      price: "Free · $31/mo",
    },
    website: "play.ht",
  },
  {
    id: "speechify",
    name: "Speechify",
    vendor: "Speechify",
    logo: "▦",
    accent: "star",
    category: "voice",
    tasks: ["Voice"],
    budget: "Freemium",
    priceNote: "Free · from $11/mo",
    rating: 4.5,
    reviews: 8920,
    tagline: "Read anything aloud — the #1 text-to-speech app.",
    description:
      "Speechify turns any text (documents, articles, PDFs, emails) into natural speech. With celebrity voices, speed reading up to 4.5x, and apps on every platform, it's the top pick for accessibility and productivity.",
    tags: ["Celebrity voices", "4.5x speed", "Cross-platform"],
    launched: "2017",
    pricing: [
      { name: "Free", price: "$0", note: "10 standard voices" },
      { name: "Premium", price: "$11/mo", note: "30+ natural voices" },
      { name: "Pro", price: "$69/mo", note: "Voice cloning + dubbing" },
    ],
    pros: ["Best-in-class reading app", "Huge voice variety", "Great accessibility tool"],
    cons: ["Pro is expensive", "Less API-focused"],
    spec: {
      bestFor: "Reading & accessibility",
      context: "—",
      imageGen: false,
      voice: true,
      codeExec: false,
      web: false,
      offline: false,
      api: false,
      price: "Free · $11/mo",
    },
    website: "speechify.com",
  },
  {
    id: "udio",
    name: "Udio",
    vendor: "Udio",
    logo: "♫",
    accent: "nebula",
    category: "voice",
    tasks: ["Voice"],
    budget: "Freemium",
    priceNote: "Free · from $10/mo",
    rating: 4.4,
    reviews: 1560,
    tagline: "Generate full songs with vocals — Suno's main rival.",
    description:
      "Udio turns a text prompt into a complete, radio-ready song with vocals, lyrics and instrumentation. Founded by ex-DeepMind researchers, it rivals Suno on quality and offers richer manual editing.",
    tags: ["Full songs", "Manual editing", "Stems export"],
    launched: "2024",
    pricing: [
      { name: "Free", price: "$0", note: "10 songs / day" },
      { name: "Standard", price: "$10/mo", note: "1200 credits + comm." },
      { name: "Pro", price: "$30/mo", note: "4800 credits" },
    ],
    pros: ["High audio quality", "More editing control than Suno", "Stem export"],
    cons: ["Smaller community", "Genre coverage still growing"],
    spec: {
      bestFor: "Music generation",
      context: "—",
      imageGen: false,
      voice: true,
      codeExec: false,
      web: false,
      offline: false,
      api: false,
      price: "Free · $10/mo",
    },
    website: "udio.com",
  },
  {
    id: "windsurf",
    name: "Windsurf",
    vendor: "Codeium",
    logo: "≋",
    accent: "teal",
    category: "coding",
    tasks: ["Coding"],
    budget: "Freemium",
    priceNote: "Free · $15/mo Pro",
    rating: 4.5,
    reviews: 1840,
    tagline: "The agentic IDE that ships features, not just completions.",
    description:
      "Windsurf (by Codeium) is an AI-first IDE where Cascade agents plan and execute multi-file changes across your codebase. It indexes your repo and runs terminal commands autonomously.",
    tags: ["Cascade agents", "Repo indexing", "Terminal access"],
    launched: "2024",
    pricing: [
      { name: "Free", price: "$0", note: "12 credits / month" },
      { name: "Pro", price: "$15/mo", note: "Unlimited credits" },
      { name: "Teams", price: "$30/mo", note: "Admin + privacy" },
    ],
    pros: ["Strong agentic workflows", "Competitive pricing", "Fast repo indexing"],
    cons: ["Newer than Cursor", "Smaller extension ecosystem"],
    spec: {
      bestFor: "Agentic coding IDE",
      context: "Repo-wide",
      imageGen: false,
      voice: false,
      codeExec: true,
      web: false,
      offline: false,
      api: false,
      price: "Free · $15/mo",
    },
    website: "codeium.com/windsurf",
  },
  {
    id: "claude-code",
    name: "Claude Code",
    vendor: "Anthropic",
    logo: "⌥",
    accent: "star",
    category: "coding",
    tasks: ["Coding", "Agents"],
    budget: "$",
    priceNote: "Included in $20/mo Pro",
    rating: 4.6,
    reviews: 2210,
    tagline: "Anthropic's terminal coding agent that lives in your shell.",
    description:
      "Claude Code is a terminal-based agentic coding tool powered by Claude. It reads your repo, runs commands, edits files and resolves issues end-to-end without leaving the shell — pair it with any editor.",
    tags: ["Terminal-native", "Agentic", "Repo-aware"],
    launched: "2025",
    pricing: [
      { name: "Pro", price: "$20/mo", note: "Includes Claude Code" },
      { name: "Max", price: "$100/mo", note: "5x usage" },
      { name: "API", price: "$3/M tok", note: "Pay per token" },
    ],
    pros: ["Editor-agnostic (terminal)", "Deep Claude reasoning", "Runs commands safely"],
    cons: ["No GUI", "Usage caps on Pro"],
    spec: {
      bestFor: "Terminal coding agent",
      context: "Repo-wide",
      imageGen: false,
      voice: false,
      codeExec: true,
      web: false,
      offline: false,
      api: true,
      price: "$20/mo Pro",
    },
    website: "anthropic.com/claude-code",
  },
  {
    id: "amazon-q",
    name: "Amazon Q Developer",
    vendor: "AWS",
    logo: "▣",
    accent: "aurora",
    category: "coding",
    tasks: ["Coding", "Data"],
    budget: "$",
    priceNote: "Free · from $19/mo",
    rating: 4.2,
    reviews: 1980,
    tagline: "AWS's AI coding assistant with cloud + security expertise.",
    description:
      "Amazon Q Developer helps you write, review and refactor code inside your IDE, with deep AWS knowledge, security scanning and inline code transformation. Enterprise tier adds business data grounding.",
    tags: ["AWS-native", "Security scan", "Code transform"],
    launched: "2024",
    pricing: [
      { name: "Free", price: "$0", note: "IDE chat + 50 scans/mo" },
      { name: "Pro", price: "$19/mo", note: "Per user, unlimited" },
      { name: "Enterprise", price: "Custom", note: "Business data + admin" },
    ],
    pros: ["Deep AWS knowledge", "Built-in security scanning", "Free tier generous"],
    cons: ["AWS-biased suggestions", "Weaker general chat"],
    spec: {
      bestFor: "AWS development",
      context: "Repo + AWS",
      imageGen: false,
      voice: false,
      codeExec: true,
      web: false,
      offline: false,
      api: true,
      price: "Free · $19/mo",
    },
    website: "aws.amazon.com/q/developer",
  },
  {
    id: "replit",
    name: "Replit AI",
    vendor: "Replit",
    logo: "⬡",
    accent: "coral",
    category: "coding",
    tasks: ["Coding", "Agents"],
    budget: "Freemium",
    priceNote: "Free · from $15/mo Core",
    rating: 4.3,
    reviews: 4120,
    tagline: "Code, run and deploy full apps from the browser.",
    description:
      "Replit AI turns natural-language prompts into working apps — it writes code, runs it in a cloud workspace, fixes errors and deploys. Agent mode handles end-to-end project creation with no local setup.",
    tags: ["Cloud IDE", "Agent mode", "1-click deploy"],
    launched: "2023",
    pricing: [
      { name: "Free", price: "$0", note: "Public repls + basic AI" },
      { name: "Core", price: "$15/mo", note: "Private + more AI" },
      { name: "Teams", price: "$30/mo", note: "Per seat, collaboration" },
    ],
    pros: ["Zero local setup", "Deploy from browser", "Great for learning"],
    cons: ["Limited for large repos", "Resource caps on free"],
    spec: {
      bestFor: "Browser app building",
      context: "Project-wide",
      imageGen: false,
      voice: false,
      codeExec: true,
      web: false,
      offline: false,
      api: false,
      price: "Free · $15/mo",
    },
    website: "replit.com",
  },
  {
    id: "you-com",
    name: "You.com",
    vendor: "You.com",
    logo: "◉",
    accent: "teal",
    category: "search",
    tasks: ["Search", "Writing"],
    budget: "Freemium",
    priceNote: "Free · from $15/mo Pro",
    rating: 4.3,
    reviews: 1640,
    tagline: "AI search with multiple modes: chat, research, create.",
    description:
      "You.com is an AI search assistant with distinct modes — Smart chat, Research (multi-step reports) and Create (images + code). It cites sources and lets you switch between frontier models.",
    tags: ["Multi-mode", "Research reports", "Model choice"],
    launched: "2022",
    pricing: [
      { name: "Free", price: "$0", note: "Limited daily queries" },
      { name: "Pro", price: "$15/mo", note: "Unlimited + GPT-4o" },
      { name: "Team", price: "$25/mo", note: "Per seat, shared" },
    ],
    pros: ["Flexible mode switching", "Strong research reports", "Picks the model"],
    cons: ["Smaller than Perplexity", "Free tier limited"],
    spec: {
      bestFor: "Multi-mode AI search",
      context: "—",
      imageGen: true,
      voice: false,
      codeExec: false,
      web: true,
      offline: false,
      api: false,
      price: "Free · $15/mo",
    },
    website: "you.com",
  },
  {
    id: "character-ai",
    name: "Character.AI",
    vendor: "Character.AI",
    logo: "☼",
    accent: "nebula",
    category: "agents",
    tasks: ["Agents", "Writing"],
    budget: "Freemium",
    priceNote: "Free · $9.99/mo Plus",
    rating: 4.2,
    reviews: 12400,
    tagline: "Chat with millions of user-created AI characters.",
    description:
      "Character.AI lets you create and chat with AI personas — fictional characters, historical figures, tutors and more. Its engaging, personality-driven chat is hugely popular, especially with younger users.",
    tags: ["Personas", "Roleplay", "Voice chats"],
    launched: "2022",
    pricing: [
      { name: "Free", price: "$0", note: "Unlimited basic chat" },
      { name: "Plus", price: "$9.99/mo", note: "Priority + faster models" },
      { name: "Pro", price: "$29.99/mo", note: "Creator tools + Cai" },
    ],
    pros: ["Huge character library", "Engaging personalities", "Great free tier"],
    cons: ["Not for productivity tasks", "Hallucinations common"],
    spec: {
      bestFor: "AI character chat",
      context: "—",
      imageGen: false,
      voice: true,
      codeExec: false,
      web: false,
      offline: false,
      api: false,
      price: "Free · $9.99/mo",
    },
    website: "character.ai",
  },
];

export const budgetTiers: { label: BudgetTier; hint: string }[] = [
  { label: "Free", hint: "No cost" },
  { label: "Freemium", hint: "Free + paid tiers" },
  { label: "$", hint: "Under $15/mo" },
  { label: "$$", hint: "$15–$50/mo" },
  { label: "$$$", hint: "$50+/mo" },
];

export const taskOptions: string[] = [
  "Writing",
  "Coding",
  "Images",
  "Video",
  "Voice",
  "Data",
  "Agents",
  "Search",
];

export function getToolById(id: string): AiTool | undefined {
  return tools.find((t) => t.id === id);
}

/**
 * Returns up to `n` tools similar to the given tool, ranked by:
 *   1. shared category (weight 3)
 *   2. shared tasks (weight 1 each)
 * Excludes the tool itself. Ties broken by rating.
 */
export function getSimilarTools(tool: AiTool, n = 3): AiTool[] {
  return tools
    .filter((t) => t.id !== tool.id)
    .map((t) => {
      let score = 0;
      if (t.category === tool.category) score += 3;
      score += t.tasks.filter((task) => tool.tasks.includes(task)).length;
      return { tool: t, score };
    })
    .sort((a, b) => b.score - a.score || b.tool.rating - a.tool.rating)
    .slice(0, n)
    .map((x) => x.tool);
}

/** Tools sorted by launch year descending (newest first). */
export function getTrendingLaunches(limit = 8): AiTool[] {
  return [...tools]
    .sort((a, b) => Number(b.launched) - Number(a.launched) || b.rating - a.rating)
    .slice(0, limit);
}
